batch_size: 128
checkpoint_directory: checkpoints/
checkpoint_interval_s: 100
critic_iter: 5
epochs: 500
evaluate: 10
learning_rate: 0.0001
noise_dim: 9
normalize: true
attack: U2R
save_model: ./saved_models/
weight_clipping: 0.01
name: u2r_r2l
